name: Staging

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301    
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish project
      run: dotnet publish -c release
      working-directory: ./src/RouteableTiles.API/
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag openplannerteam/routeable-tiles-api:staging --tag openplannerteam/routeable-tiles-api:staging-0.$GITHUB_RUN_NUMBER
      working-directory: ./src/RouteableTiles.API/
    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u openplannerteam --password-stdin
